name: Doc Build on Merge to `master`

# Controls when the action will run. Triggers the workflow on push
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        path: ''

    - uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - run: npm install -D
    - run: npm run doc

    ## NOTE: Need to copy demo to docs/ directory manually in this action, will want to remove this if copied to another project
    - run: cp -r public/ docs/demo/
    - run: git status

    - uses: EndBug/add-and-commit@v4 # You can change this to use a specific version
      with:
        add: docs
        author_name: DocBuilder
        author_email: devlinjunker@gmail.com
        message: 'Build Docs on Commit to Master'
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}


    # TODO: Uncomment after setting up wiki

    # - run: node ./scripts/actions/collect-wiki.js
    #
    # # from: https://github.com/marketplace/actions/wiki-page-creator-action
    # - name: Upload READMEs to Wiki
    #   uses: docker://decathlon/wiki-page-creator-action:latest
    #   env:
    #     ACTION_MAIL: devlin.junker@gmail.com
    #     ACTION_NAME: devlinjunker
    #     GH_PAT: ${{ secrets.GH_PAT }}
    #     MD_FOLDER: ./wiki
    #     OWNER: devlinjunker
    #     REPO_NAME: template.hapi.rest
    #     SKIP_MD: README.md
